### PR TITLE
minor: #212/print errors in writeErrorFile when not found

### LINKED ISSUE #212: Print out error message when no ErrorsFile can be found
Created from issue #211 

When debugging a separate problem, I couldn't understand the actual problem, since there was no error message outputted. As shown below, it just prints out a generic "no such file or directory":
325196728-a3d19940-ba27-46e5-9015-b0e03e88161d
```
ERROR Please check the format config file unexpected end of JSON input
no such file or directory
Could not read file at location: .
Please ensure the file exists and is formatted correctly.
ERROR no such file or director
```

It turns out it was because I ran the binary in a Docker Image, and I think it was missing some permissions to write the ErrorsFile. 
And when the code runs into an error and tries to print out a failure message, if the ErrorsFile cannot be read/found in the "writeErrorFile" function here: https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/blob/develop/utils.go#L371
Then it will fail with the above shown message about it not being able to read the file.
The errors in the "writeErrorFile" are not handled, and this makes sense, since it usually does not make sense to print errors when trying to read error messages.

But my suggestion is to just output a generic error message, saying that no files were found when looking for other errors.

### PR DESCRIPTION
**Pull request by tonur**
- [ ] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [ ] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does
Closes #212 
Adds error messages when errorsfiles cannot be find, to make debugging effort easier in the future.

### Notes for the reviewer
Please review if the logs are written to your standards.

### More information

- [Link to documentation](https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/wiki/)

### Screenshots
To add more context, as this doesn't help that much:
325766946-a930d223-b047-4299-8f57-d41940ea114a

### CODE REVIEW

**Review by aarlaud — APPROVED** [review]

File: utils.go [hunk 1]
```diff
@@ -374,10 +374,17 @@ func writeErrorFile(function string, errorText string, customDebug debug) {
 
 	// Get filePath
 	filename, err := FindFile("ErrorsFile")
+	if err != nil {
+		workingDir, _ := os.Getwd()
+		log.Println("*** ERROR *** Could not find any ErrorsFiles in the working directory at %s", workingDir, err)
```
Comment (tonur) [inline utils.go:379]: This line added an error in the CircleCI build, looking into it at the moment
